### ISSUE TITLE
Number of Confirmations and Timer

### ISSUE THREAD

**Issue by ryconnolly** [blockonomics/woocommerce-plugin#34] opened 2017-11-22 09:46 UTC
Hi,

Would it be possible to add admin options to set the number of confirmations before setting order to processing and changing the timer?
For example, I'll be changing mine to 0 confirmations and 20 minutes.  However, having that as an option would be nice so it's not reverted with updates.

**Comment by blockonomics** [comment] 2017-11-22 12:03
Interesting, others have asked for this. However, zero is not at all safe (We want to give a warning before merchant does this). Similar, very high time period is risky because price will change a lot

Implementation is straightforward. Just needs to make show necessary wanings

**Comment by ryconnolly** [comment] 2017-11-22 18:35
I agree, warnings would be good.
In my case I've seen small payments that take well over an hour to receive first confirmation which is why I decided to switch to 0 confirmations.

**Comment by shivaenigma** [comment] 2017-12-27 13:18
Added in [version 1.4.3](https://wordpress.org/plugins/blockonomics-bitcoin-payments/#developers)

**Comment by shivaenigma** [comment] 2017-12-27 13:26
Closing for now. Number of confirmation option is very risky. Will be added after after having some facility on backend to analyse unconfirmed TX

**Closed by shivaenigma** 2017-12-27 13:26 UTC
