### ISSUE TITLE
Not picking up orders sent after 10 minutes

### ISSUE THREAD

**Issue by astupidmoose** [blockonomics/woocommerce-plugin#15] opened 2017-09-05 07:35 UTC
Currently there is a 10 minute timer on payments. 

This presents a problem for some people who are using custodial wallets, such as exchanges, where they might not see their transaction being broadcast until after the 10 minute time is over. 

When a payment does come in after the timer has expired (say in 30 minutes), its not applied to the order.

**Comment by blockonomics** [comment] 2017-09-05 14:32
> When a payment does come in after the timer has expired (say in 30 minutes), its not applied to the order.
This is by design in 30 minutes, the bitcoin price would change and merchant can end up in loss. For example, the customer could cleverly wait for an hour for price to increase and then  make the payment.

Most payment processors don't give a window more than 15 minutes. Even 10 minutes is too much time for price to fluctuate! But you cannot keep changing the price every minute, so you take a risk of 10 minute window. Please note that the payment need not confirm in these 10 minutes. Confirmation can happen in days, but the unconfirmed tx must come in that time. 

In future we can give a config to set this to 15/20 minute, but merchant must understand the risks here.  If you want this urgently, you can change these lines
- https://github.com/blockonomics/woocommerce-plugin/blob/master/blockonomics-woocommerce.php#L235. Change 600 to 900
- https://github.com/blockonomics/woocommerce-plugin/blob/master/js/app.js#L42. Change 10*60 to 15*90

**Comment by blockonomics** [comment] 2017-09-06 04:23
By the way forgot to mention, thanks a lot for logging these. Critical for our product development. Keep them coming :smiley:

**Comment by shivaenigma** [comment] 2017-10-05 11:11
This is fixed in 1.3.9 release. Since, shapshift conversions sometime take upto half a day, we cannot restrict ourselves on backend. The payment is now accepted, with a warning note

https://github.com/blockonomics/woocommerce-plugin/blob/master/blockonomics-woocommerce.php#L232

**Closed by shivaenigma** 2017-10-05 11:11 UTC
Labels: enhancement
